APP_TITLE = ""

USERNAME = ""

PASSWORD = ""

PRIMARY_COLOR = ""

SECONDARY_COLOR = ""

BACKGROUND = ""

LOGO = ""

# AZURE_DOC_INTELLIGENCE_ENDPOINT = ""
# AZURE_DOC_INTELLIGENCE_KEY = ""

# AZURE_DOC_INTELLIGENCE_ENDPOINT = ""
# AZURE_DOC_INTELLIGENCE_KEY = ""
AZURE_DOC_INTELLIGENCE_ENDPOINT = ""
AZURE_DOC_INTELLIGENCE_KEY = ""

# DEPLOYMENT_NAME = ""
# DEPLOYMENT_ENDPOINT=""
# DEPLOYMENT_KEY=""

DEPLOYMENT_NAME = ""
DEPLOYMENT_ENDPOINT=""
DEPLOYMENT_KEY=""